### ISSUE TITLE
Trigger too late because of transform: translateY(-50%);

### ISSUE THREAD

**Issue by iampuma** [jlmakes/scrollReveal.js#167]
Currently I am using the following snippet to vertical align my content in a div:

```css
.valign { 
  position: relative; 
  top: 50%; 
  transform: translateY(-50%); 
}
```
This causes scrollReveal to trigger the animation when it is at the half of the content and after finishing the animation it will stutter to its normal position. I have created a jsfiddle to show the problem http://jsfiddle.net/dm00e87q/3/ (cookies slide in the jsfiddle, can show the issue the clearest)

A solution would be appreciated. Thanks for the help!

**Comment by jlmakes** [comment]
Hey @iampuma 

Generally speaking, I would not recommend this technique:
```css
.valign { 
  position: relative; 
  top: 50%; 
  transform: translateY(-50%); 
}
```
The primary reason being that using `transform: translate` can result in sub-pixel positioning with odd computed heights, which causes the browser to [render blurry content](http://jsfiddle.net/quLqxor9/).

_Plus_, in this instance, your styles conflict with ScrollReveal’s use of `transform` for its animations (I believe this is what your original question was about):
![conflict](https://cloud.githubusercontent.com/assets/2044842/9300325/70c4a2ec-4479-11e5-9fe8-e3d70c3ce5e5.gif)

#### What I recommend...

Remove the `.valign` class altogether, and instead use [CSS Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) to center your content:
```css
.container {
    display: flex;
    align-items: center;
    height: 600px;
}
```
I removed the delay from your demo (for faster troubleshooting), but you can see an updated demo using this new container; there is no style conflict, and no timing/visibility issues.
