### ISSUE TITLE
Revealed elements cannot be easily printed

### ISSUE THREAD

**Issue by tribut** [jlmakes/scrollreveal.js#242]
When scrollreveal is being used, only already revealed elements can be printed. Would it be possible to avoid this using a CSS media query?

**Comment by jlmakes** [comment]
Hmm, good question.
I suppose if you were using `sr.reveal('.reveal')` you could try something like:
```css
@media print {
    .reveal {
        opacity: 1 !important;
        visibility: visible !important;
    }
}
```
