### ISSUE TITLE
Force reset and repeat animation while element is in viewport?

### ISSUE THREAD

**Issue by JanSchmidhofer** [jlmakes/scrollreveal.js#290]
I have 8 elements that fade in one after the other, each taking 1s -- after that though, they should fade out all together, and then repeat the animation (while in the viewport).

It's not possible to start a "reset" manually?

**Comment by jlmakes** [comment]
If you create a class with the desired looping animation, you can add it to the element using the `config.afterReveal` callback.

_Example:_
```css
.my-animation {
  animation-iteration-count: infinite;
  animation-name: myAnimation;
}

@keyframes myAnimation {
  from {
    transform: scale(1.1);
  }

  to {
      transform: scale(0.9);
  }
}
```
```js
var sr = new ScrollReveal();

// create a configuration object with a callback
// to add the class to the element after the reveal.
var config = { 
  afterReveal: function (el) {
    el.classList.add('my-animation');
  }
};

sr.reveal('.my-element', config);
```
