### ISSUE TITLE
Hide an div when another is visible.

### ISSUE THREAD

**Issue by marcelo-kazalukian** [jlmakes/scrollreveal.js#291]
I have an div that is always visible. I need to hide it only when the footer is shown. It's possible?

**Comment by jlmakes** [comment]
You should be able to use the reveal callbacks to add the desired behavior.

_Example:_
```css
.my-div {
  opacity: 1;
  transition: opacity 0.2s;
}
.my-div.my-div--hidden {
  opacity: 0;
}
```
```js
var sr = new ScrollReveal();
var myDiv = document.querySelector('.my-div');

var toggleMyDiv = { 
  afterReveal: function (el) {
    myDiv.classList.add('.my-div--hidden');
  },
  afterReset: function (el) {
    myDiv.classList.remove('.my-div--hidden');
  }
};

sr.reveal('.footer', toggleMyDiv);
```
