### ISSUE TITLE
animate.css

### ISSUE THREAD

**Issue by PDX1337** [jlmakes/scrollreveal.js#296]
hi long time agoo i know there are some threads alreaedy BUT..

is there no way to add animate.css class ? maby after a animation  with .addClass ?

Regards
PDX

**Comment by jlmakes** [comment]
ScrollReveal generates/manages lot of styles to create reveal animations so you don't have to; if you're not looking to use that behavior, you may be better off using a different library.

Since you asked though, I hacked together a solution that "disables" ScrollReveal's animations, and toggles a class instead.
```js
var noReveal = {
  distance: 0,
  duration: 0,
  opacity: 1,
  scale: 1,
  viewFactor: 0,
  reset: true // required for "toggle"
}

var sr = new ScrollReveal(noReveal);

sr.reveal('.foo', {
  beforeReveal: function (el) {
    el.classList.add('someClass');
  },
  beforeReset: function (el) {
    el.classList.remove('someClass');
  }
});
```

It's important to note that ScrollReveal generates transition styles, so if you're looking to transition your own (or Animate.css) propreties, you're going to have override that with an `!important`...

```css
.foo {
  background-color: black;
  color: white;
  height: 40px;
  margin-bottom: 20px;

  transition: background-color 2s !important; /* required */
}

.foo.someClass {
  background-color: red;
}
```

Here's a [JSBin demonstrating the above](http://jsbin.com/xuceso/edit?html,css,js,output).
